version: "3"
services:
  backend:
    container_name: "backend"
    build:
      context: './backend'
      dockerfile: "./dockerfile"
    ports:
      - "4000:4000"


  frontend:
    container_name:  "frontend"
    build:
      context: './frontend'
      dockerfile: "./dockerfile"
    ports:
      - "80:80"
    depends_on:
      - backend
    links:
      - backend
    environment:
      - REACT_APP_APIURL=http://backend:4000




